trigger: none




variables:
  workdir: '$(Build.SourcesDirectory)/Infrastructures/Dev'
  

pool:
 name: todoagent

stages:
  - stage: 
    displayName: terraform init and plan 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
 
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(workdir)
            backendServiceArm: 'first'
            backendAzureRmStorageAccountName: 'backacc123322121'
            backendAzureRmContainerName: 'backend'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(workdir)

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(workdir)
            environmentServiceNameAzureRM: 'first'

  - stage:

    condition: succeeded()
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(workdir)
            backendServiceArm: 'first'
            backendAzureRmStorageAccountName: 'backacc123322121'
            backendAzureRmContainerName: 'backend'
            backendAzureRmKey: 'terraform.tfstate'



        