trigger: none






pool:
 name: todoagent


stages:
  - stage: 
    displayName: terraform init and plan 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
 
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Build.SourcesDirectory)/Infrastructures/Dev'
            backendServiceArm: 'first'
            backendAzureRmStorageAccountName: 'backacc123322121'
            backendAzureRmContainerName: 'backend'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructures/Dev'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(Build.SourcesDirectory)/Infrastructures/Dev'
            environmentServiceNameAzureRM: 'first'

            